name: pyclass
channels:
  - conda-forge
dependencies:
  # required
  - python=3.10
  - pip

  - numpy
  - matplotlib # =3.4.3

  - jupyter
  - jupytext
  - jupyterlab
  # - git
  - python-dateutil
  - affine
  - scipy
  - openpyxl
  - xlrd
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - rasterstats
  - flopy
  - fiona # >=1.8.21
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - geopandas
  - cartopy
  - vtk
  - xarray
  - pyyaml
  - rtree
  - requests
  - pytest
  - statsmodels
  - pygeohydro # =0.13.6
  - pynhd
  - pydaymet
  - async-retriever
  - hydrofunctions

  - pip:
    - installation/dataretrieval-1.0.2-py3-none-any.whl
    # - git+https://github.com/DOI-USGS/dataretrieval-python@master
      # - gis-utils
    # - git+https://github.com/modflowpy/flopy@develop
      # - git+https://github.com/doi-usgs/sfrmaker@develop
      # - git+https://github.com/doi-usgs/modflow-setup@develop
      # - utm
